name: Auto-trigger-render

on:
  schedule:
    - cron: "0 */2 * * *"  # Triggers every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger endpoint
        run: |
          curl -X POST https://socialfinet-v1.onrender.com/post-on-ping
